# Generated by Django 4.0.3 on 2022-09-20 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_user_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='number',
            field=models.CharField(blank=True, default=0, max_length=50, null=True, verbose_name='number'),
        ),
    ]
