# Generated by Django 4.0.3 on 2022-09-26 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_user_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Full_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='نام کامل'),
        ),
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='UserImage', verbose_name='عکس'),
        ),
        migrations.AlterField(
            model_name='user',
            name='number',
            field=models.CharField(blank=True, default=0, max_length=50, null=True, verbose_name='شماره تلفن'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='نام کاربری'),
        ),
    ]
