# Generated by Django 4.0.3 on 2022-09-03 18:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='posts',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes2', to='blog.post', verbose_name='مقاله'),
        ),
        migrations.AlterField(
            model_name='like',
            name='users',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes2', to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
    ]
