# Generated by Django 4.0.3 on 2022-09-05 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='time',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
