# Generated by Django 4.0.3 on 2022-09-26 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_remove_post_title_post_title2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title1',
            field=models.CharField(default=1, max_length=50, verbose_name='اسم پست به اینگلیسی و اصلی'),
            preserve_default=False,
        ),
    ]
