# Generated by Django 4.0.3 on 2022-09-26 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_post_title1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='title1',
        ),
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.CharField(default=1, max_length=50, verbose_name='اسم پست به اینگلیسی و اصلی'),
            preserve_default=False,
        ),
    ]
