# Generated by Django 4.0.3 on 2022-09-28 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_notification_seen'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='seen',
            new_name='seens',
        ),
    ]
